version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: SimpleBlog/Dockerfile
    networks:
    - db
  db:
    image: postgres
    environment: 
        POSTGRES_PASSWORD: password
    ports: 
    - "5432:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    networks:
    - db

networks:
  db:
    driver: bridge